title: 'Building Makers'
default_lang: en
author:
  name: 'Sara Gonzalez'
  email: saragonz@ufl.edu
taxonomies:
  - pubdate
  - audience
  - expertise
  - subject
  - keywords
metadata:
  description: 'An online bibliography for maker-related books and websites'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
